Browser("Login | Salesforce").Page("Login | Salesforce").Link("Try for Free").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Login | Salesforce").Link("Try for Free")_;_script infofile_;_ZIP::ssf1.xml_;_
OptionalStep.Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebElement("optanon-popup-bg").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebElement("optanon-popup-bg")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebButton("Accept and Continue").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebButton("Accept and Continue")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserFirstName").Set "fname" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserFirstName")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserLastName").Set "lname" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserLastName")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserEmail").Set DataTable("UserName", dtGlobalSheet) @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserEmail")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserTitle").Set "egnineer" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserTitle")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserPhone").Set "3035551212" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("UserPhone")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("CompanyName").Set "MyFirstCompany" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebEdit("CompanyName")_;_script infofile_;_ZIP::ssf9.xml_;_
'Browser("Login | Salesforce").WinObject("Blank Page - Internet").Page("Page").Sync
'WinObject("Internet Explorer_Server").Window("DCompTargetWindow").Click 294,18
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyEmployees").Select "1 - 20 employees" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyEmployees")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyCountry").Select "United States" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyCountry")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyState").Select "Colorado" @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebList("CompanyState")_;_script infofile_;_ZIP::ssf14.xml_;_
'WinObject("Internet Explorer_Server").Window("DCompTargetWindow").Click 36,133
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebElement("Agree to Master Agreement").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebElement("WebElement")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebButton("start my free trial").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com").WebButton("start my free trial")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Login | Salesforce").Page("Free Trial - Salesforce.com_2").WebButton("start my free trial").Click @@ hightlight id_;_Browser("Login | Salesforce").Page("Free Trial - Salesforce.com 2").WebButton("start my free trial")_;_script infofile_;_ZIP::ssf18.xml_;_
