Browser("Login | Salesforce").OpenNewTab @@ hightlight id_;_329174_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Browser").Page("Page").Sync @@ hightlight id_;_Browser("Browser").Page("Page")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Browser").Navigate "http://yopmail.com/" @@ hightlight id_;_525134_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Browser").Page("YOPmail - Disposable Email").WebEdit("login").Set DataTable("InUserName", dtGlobalSheet) @@ hightlight id_;_Browser("Browser").Page("YOPmail - Disposable Email").WebEdit("login")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Browser").Page("YOPmail - Disposable Email").WebButton("Check Inbox").Click @@ hightlight id_;_Browser("Browser").Page("YOPmail - Disposable Email").WebButton("Check Inbox")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Browser").Page("YOPmail - Disposable Email").Frame("ifmail").Link("Verify Account").Click @@ hightlight id_;_Browser("Browser").Page("YOPmail - Disposable Email").Frame("ifmail").Link("Verify Account")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("newpassword").set "1qaz@WSX" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("newpassword")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("confirmpassword").Set "1qaz@WSX" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("confirmpassword")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("answer").Set "Denver" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("answer")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebButton("Change Password").Click @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebButton("Change Password")_;_script infofile_;_ZIP::ssf11.xml_;_
