'Browser("Salesforce Developers").OpenNewTab @@ hightlight id_;_852648_;_script infofile_;_ZIP::ssf22.xml_;_
'Browser("Salesforce Developers").Page("Salesforce Developers").Sync @@ hightlight id_;_Browser("Salesforce Developers").Page("Salesforce Developers")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Salesforce Developers").Navigate "http://yopmail.com/" @@ hightlight id_;_852648_;_script infofile_;_ZIP::ssf24.xml_;_

Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").WebEdit("login").Set DataTable("newUserName", dtGlobalSheet) @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").WebEdit("login")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").WebButton("Check Inbox").Click @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").WebButton("Check Inbox")_;_script infofile_;_ZIP::ssf2.xml_;_
'Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail").Image("Get a Tour").Click @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail").Image("Get a Tour")_;_script infofile_;_ZIP::ssf3.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Trailhead Basics | Salesforce").WebButton("Login").Click @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Trailhead Basics | Salesforce").WebButton("Login")_;_script infofile_;_ZIP::ssf4.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Login | Trailhead").WebButton("Salesforce").Click @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Login | Trailhead").WebButton("Salesforce")_;_script infofile_;_ZIP::ssf5.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Login | Salesforce").WebEdit("username").Set DataTable("newUserName", dtGlobalSheet) @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Login | Salesforce").WebEdit("username")_;_script infofile_;_ZIP::ssf6.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Login | Salesforce").Link("Forgot Your Password?").Click @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Login | Salesforce").Link("Forgot Your Password?")_;_script infofile_;_ZIP::ssf7.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Forgot Your Password |").WebEdit("un").Set DataTable("newEmail", dtGlobalSheet) @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Forgot Your Password |").WebEdit("un")_;_script infofile_;_ZIP::ssf8.xml_;_
'Browser("Trailhead Basics | Salesforce").Page("Forgot Your Password |").WebButton("Continue").Click @@ hightlight id_;_Browser("Trailhead Basics | Salesforce").Page("Forgot Your Password |").WebButton("Continue")_;_script infofile_;_ZIP::ssf9.xml_;_
'Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Link("Check for new mails").Click' @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Link("Check for new mails")_;_script infofile_;_ZIP::ssf10.xml_;_
'Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail_2").Link("https://na136.salesforce.com/s").Click @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail 2").Link("https://na136.salesforce.com/s")_;_script infofile_;_ZIP::ssf11.xml_;_
'Browser("Answer Your Security Question").Page("Answer Your Security Question").WebEdit("answer").Set "denver" @@ hightlight id_;_Browser("Answer Your Security Question").Page("Answer Your Security Question").WebEdit("answer")_;_script infofile_;_ZIP::ssf12.xml_;_
'Browser("Answer Your Security Question").Page("Answer Your Security Question").WebButton("Continue").Click @@ hightlight id_;_Browser("Answer Your Security Question").Page("Answer Your Security Question").WebButton("Continue")_;_script infofile_;_ZIP::ssf13.xml_;_
'Browser("Answer Your Security Question").Page("Answer Your Security Question_2").WebButton("Continue").Click @@ hightlight id_;_Browser("Answer Your Security Question").Page("Answer Your Security Question 2").WebButton("Continue")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifinbox").Link("mailFrom_developer@salesforce.com").Click @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifinbox").Link("10:45developer@salesforce.comW")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail_3").Link("Verify Account").Click @@ hightlight id_;_Browser("YOPmail - Disposable Email").Page("YOPmail - Disposable Email").Frame("ifmail 3").Link("Verify Account")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("newpassword").Set"1qaz@WSX" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("newpassword")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("confirmpassword").Set "1qaz@WSX" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("confirmpassword")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebEdit("answer").Set "denver" @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebEdit("answer")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Change Your Password |").Page("Change Your Password |").WebButton("Change Password").Click @@ hightlight id_;_Browser("Change Your Password |").Page("Change Your Password |").WebButton("Change Password")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Change Your Password |").Page("Home Page ~ Salesforce").WebButton("No Thanks").Click @@ hightlight id_;_Browser("Change Your Password |").Page("Home Page ~ Salesforce").WebButton("No Thanks")_;_script infofile_;_ZIP::ssf21.xml_;_
